### ISSUE TITLE
[Question] What's the difference between manifestPlaceholders in android gradle plugin ?

### ISSUE THREAD

**Issue by YangCheung** [castorflex/manifestreplace-plugin#1]
Hi,

I'm sorry. I just want to konw what's the difference between android gradle plugin ?

Such as 

```
defaultConfig {
    manifestPlaceholders = [ activityName:"defaultName"]
}
```

Thanks !

**Comment by castorflex** [comment]
Hi,

The android-plugin handles the placeholders only in a few cases (e.g. the activity's label, the package name, etc.). You cannot have a placeholder for a whole intentFilter or a whole activity.

Hope I answered your question

**Comment by YangCheung** [comment]
Got it.

Thanks.
