### ISSUE TITLE
ManifestReplacePlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by nadavfima** [castorflex/manifestreplace-plugin#2]
Tried adding the lib to my project, but got this error.
any ideas?

**Comment by castorflex** [comment]
Yep, I compile the project with Java 8, I will have a look asap :) 
In the meantime, you can clone and `gradle install` it to use it locally (mavenLocal())

**Comment by castorflex** [comment]
v1.1.1 pushed to maven central
